function [shapes, shape_min, shape_max] = variable_shape(N, c_f, delta, epsilon)
% This function generates the variable shape parameter
% N is the number of centers.
% c_f is the shape parameter generated by the modified Franke function
% delta is the error tolerance
% epison is also the error tolerance usuallly set to 0.5

shape_min = max(delta, c_f - epsilon);
shape_max = c_f + epsilon;

samples = haltonset(1, 'Skip', 500);
shapes = shape_min + (shape_max-shape_min)*net(samples, N)';

end
